// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Auth struct {
	ID    string `json:"id"`
	Token string `json:"token"`
}

type ExternalLink struct {
	ID           string  `json:"id"`
	PrefectureID string  `json:"prefecture_id"`
	Title        string  `json:"title"`
	URL          string  `json:"url"`
	CreatedAt    *string `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
}

type Prefecture struct {
	ID            string          `json:"id"`
	No            int             `json:"no"`
	IsPublished   bool            `json:"is_published"`
	Region        string          `json:"region"`
	Name          string          `json:"name"`
	Quantities    []*Quantity     `json:"quantities"`
	ExternalLinks []*ExternalLink `json:"external_links"`
	CreatedAt     *string         `json:"created_at"`
	UpdatedAt     string          `json:"updated_at"`
}

type Quantity struct {
	ID           string  `json:"id"`
	PrefectureID string  `json:"prefecture_id"`
	Date         string  `json:"date"`
	Positive     int     `json:"positive"`
	Discharge    int     `json:"discharge"`
	Death        int     `json:"death"`
	SickbedTotal int     `json:"sickbed_total"`
	CreatedAt    *string `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
}

type User struct {
	ID           string  `json:"id"`
	PrefectureID string  `json:"prefecture_id"`
	Email        string  `json:"email"`
	Password     string  `json:"password"`
	CreatedAt    *string `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
}
